package com.nesterov.veld.design_system.theme

fun veldLight() = VeldColors(
    materialColors = materialLightColorScheme,
    textColorPrimary = vi_theme_light_textColorPrimary,
    textColorSecondary = vi_theme_light_textColorSecondary,
    textColorTertiary = vi_theme_light_textColorTertiary,
    necromancySpell = vi_theme_light_necromancySpell,
    conjurationSpell = vi_theme_light_conjurationSpell,
    evocationSpell = vi_theme_light_evocationSpell,
    illusionSpell = vi_theme_light_illusionSpell,
    abjurationSpell = vi_theme_light_abjurationSpell,
    divinationSpell = vi_theme_light_divinationSpell,
    transmutationSpell = vi_theme_light_transmutationSpell,
    enchantmentSpell = vi_theme_light_enchantmentSpell,
    charisma = vi_theme_light_charisma,
    dexterity = vi_theme_light_dexterity,
    strength = vi_theme_light_strength,
    wisdom = vi_theme_light_wisdom,
    intelligence = vi_theme_light_intelligence,
    constitution = vi_theme_light_constitution,
    isLight = true,
)

fun veldDark() = VeldColors(
    materialColors = materialDarkColorScheme,
    textColorPrimary = vi_theme_dark_textColorPrimary,
    textColorSecondary = vi_theme_dark_textColorSecondary,
    textColorTertiary = vi_theme_dark_textColorTertiary,
    necromancySpell = vi_theme_dark_necromancySpell,
    conjurationSpell = vi_theme_dark_conjurationSpell,
    evocationSpell = vi_theme_dark_evocationSpell,
    illusionSpell = vi_theme_dark_illusionSpell,
    abjurationSpell = vi_theme_dark_abjurationSpell,
    divinationSpell = vi_theme_dark_divinationSpell,
    transmutationSpell = vi_theme_dark_transmutationSpell,
    enchantmentSpell = vi_theme_dark_enchantmentSpell,
    charisma = vi_theme_dark_charisma,
    dexterity = vi_theme_dark_dexterity,
    strength = vi_theme_dark_strength,
    wisdom = vi_theme_dark_wisdom,
    intelligence = vi_theme_dark_intelligence,
    constitution = vi_theme_dark_constitution,
    isLight = false,
)